"""The compiled single-file manuscript, plus clean text for downstream work.

`build/manuscript.md` is the canonical compiled source: the whole book in one
file, regenerated from chapters/ on every build. It is never edited by hand —
edit the chapter files and rebuild.

`build/text/` holds one markup-free .txt per chapter. That is the feedstock for
translation, TTS/voiceover, and the plagiarism check, none of which want
Markdown syntax in the way.
"""

from __future__ import annotations

import re

from . import boilerplate, config
from .sources import Book, _plain_text


def _matter_md(page) -> str:
    out = []
    if page.heading and page.kind not in ("half-title", "title-page"):
        out.append(f"## {page.heading}\n")
    elif page.heading:
        out.append(f"## {page.heading}\n")
    body = _plain_text(page.html)
    if body:
        out.append(body)
    return "\n".join(out).strip()


def build_manuscript(book: Book) -> str:
    """Assemble the whole book into one Markdown document."""
    lines: list[str] = []

    lines.append("---")
    lines.append(f'title: "{config.TITLE}"')
    lines.append(f'subtitle: "{config.SUBTITLE}"')
    lines.append(f'author: "{config.AUTHOR_DISPLAY}"')
    lines.append(f'language: "{config.LANGUAGE}"')
    lines.append(f'chapters: {len(book.chapters)}')
    lines.append(f'words: {book.word_count}')
    lines.append("generated_by: tools/build.py  # do not edit this file by hand")
    lines.append("---")
    lines.append("")

    # The half-title, title page and copyright page are generated rather than
    # file-backed (see html.py), so they are reconstructed here to keep the
    # compiled manuscript a faithful copy of the whole book.
    lines.append(f"# {config.TITLE}\n")
    lines.append(f"*{config.SUBTITLE}*\n")
    lines.append(f"{config.AUTHOR_DISPLAY}\n")
    imprint = f"{config.IMPRINT} · {config.IMPRINT_CITY}" if config.IMPRINT_CITY else config.IMPRINT
    lines.append(f"{imprint}")
    lines.append("\n---\n")

    supplied = {p.kind for p in book.front}
    if "copyright" not in supplied:
        lines.append(f"## {boilerplate.copyright_heading()}\n")
        for css, para in boilerplate.copyright_blocks():
            body = "\n".join(para)
            lines.append(f"*{body}*\n" if css == "cp-title" else f"{body}\n")
        lines.append("\n---\n")

    for page in book.front:
        if page.unfilled:
            continue
        lines.append(_matter_md(page))
        lines.append("\n---\n")

    for ch in book.chapters:
        lines.append(f"## {ch.heading_plain}\n")
        body = f"\n\n{config.SCENE_BREAK}\n\n".join(_plain_text(s) for s in ch.scenes)
        lines.append(body)
        lines.append("\n---\n")

    for page in book.back:
        if page.unfilled:
            continue
        lines.append(_matter_md(page))
        lines.append("\n---\n")

    text = "\n".join(lines)
    return re.sub(r"\n{4,}", "\n\n\n", text).strip() + "\n"


def write_manuscript(book: Book) -> None:
    config.BUILD_DIR.mkdir(parents=True, exist_ok=True)
    config.OUT_MANUSCRIPT.write_text(build_manuscript(book), encoding="utf-8")


def write_text_exports(book: Book) -> None:
    """One clean .txt per chapter for translation / TTS / plagiarism checking."""
    config.OUT_TEXT_DIR.mkdir(parents=True, exist_ok=True)
    for old in config.OUT_TEXT_DIR.glob("*.txt"):
        old.unlink()
    for ch in book.chapters:
        out = config.OUT_TEXT_DIR / f"{ch.slug}-{ch.voice}.txt"
        out.write_text(ch.text + "\n", encoding="utf-8")

    full = "\n\n\n".join(ch.text for ch in book.chapters)
    (config.OUT_TEXT_DIR / "full-book.txt").write_text(full + "\n", encoding="utf-8")
