"""Generate the KDP metadata sheet.

KDP has no publishing API, so the upload itself is a manual web form. This
file exists to make that form a copy-paste exercise: every field KDP asks for,
pre-filled, alongside the computed print specification and the exact files to
upload.
"""

from __future__ import annotations

import re

from . import config as c
from .sources import Book, blurb_blocks

# Suggestions only — worth checking against what comparable titles actually
# rank under before publishing.
KEYWORDS = [
    "romantic suspense",
    "artificial intelligence novel",
    "AI love story",
    "love story with a secret",
    "speculative literary fiction",
    "artificial general intelligence",
    "science fiction romance",
]

CATEGORIES = [
    "Literature & Fiction > Literary Fiction > Mystery, Thriller & Suspense",
    "Literature & Fiction > Literary Fiction > Romance",
    "Science Fiction & Fantasy > Science Fiction > General",
]

# KDP print cost, US marketplace, black ink on cream paper.
PRINT_FIXED_USD = 0.85
PRINT_PER_PAGE_USD = 0.012


def _blurb() -> str:
    """The description copy from book-matter/blurb.md.

    A translation may not have its blurb written yet — that is marketing copy,
    not book content, and it must not stop the edition from building.
    """
    blocks = blurb_blocks()
    if not blocks:
        return (f"[No blurb for the {c.EDITION_NAME} edition — write "
                f"{(c.MATTER_DIR / 'blurb.md').relative_to(c.ROOT)} and rebuild.]")
    return "\n\n".join(blocks)


# The figure `pricing-notes.md` was written against, at an assumed 300 pages.
PRICING_NOTES_ESTIMATE_USD = 4.45


def _vs_estimate(print_cost: float) -> str:
    delta = print_cost - PRICING_NOTES_ESTIMATE_USD
    if abs(delta) < 0.05:
        return "in line with"
    return f"${abs(delta):.2f} {'above' if delta > 0 else 'below'}"


def write_metadata(book: Book, cover: dict) -> None:
    pages = cover["page_count"]
    print_cost = PRINT_FIXED_USD + PRINT_PER_PAGE_USD * pages
    # Launch prices decided 2026-09-11: debut sweet spot, ebook in the 70%
    # band and ≥20% under the paperback. Details in pricing-notes.md.
    pb_list = 14.99
    eb_list = 4.99

    kw = "\n".join(f"{i}. {k}" for i, k in enumerate(KEYWORDS, 1))
    cats = "\n".join(f"{i}. {k}" for i, k in enumerate(CATEGORIES, 1))

    doc = f"""# KDP metadata — {c.TITLE}

Generated by `tools/build.py`. Every field below maps to a box in the KDP
title setup at kdp.amazon.com. Nothing here is uploaded automatically — KDP
has no publishing API, so this sheet is the input to a manual form.

## Book details

| KDP field | Value |
|---|---|
| Book title | {c.TITLE} |
| Subtitle | {c.SUBTITLE} |
| Series | — |
| Edition number | 1 |
| Author (primary) | {c.AUTHOR_METADATA} |
| Language | English |
| Publication date | leave blank (KDP uses the approval date) |
| Publisher | {c.IMPRINT} |
| ISBN (paperback) | {c.ISBN_PAPERBACK} — choose "Get a free KDP ISBN" |
| ISBN (ebook) | not required; Amazon assigns an ASIN |

## Description

Paste into the **Book Description** field. Light HTML is accepted there; the
listing truncates after roughly two lines, so the opening question does the
work.

```
{_blurb()}
```

## Keywords (7 slots)

{kw}

## Categories (up to 3)

{cats}

## Content and rights

- **Publishing rights:** you own the copyright and hold exclusive rights.
- **AI content disclosure:** answer **yes** — this manuscript is AI-assisted
  (drafted with an AI collaborator, author-directed) and the **cover art is
  AI-generated**. KDP asks separately about text and images; disclose both.
- **Age range / low content:** not applicable.
- **Reading age:** adult.

## Print specification (paperback)

| Item | Value |
|---|---|
| Trim size | {c.TRIM_W_IN:g}" × {c.TRIM_H_IN:g}" |
| Interior | black & white on {c.PAPER} paper |
| Bleed | no bleed (interior); cover has {c.BLEED_IN}" bleed |
| Page count | **{pages}** |
| Spine width | **{cover['spine_in']:.4f}"** ({cover['spine_px']} px @ {c.COVER_DPI} dpi) |
| Full cover size | {cover['cover_w_in']:.4f}" × {cover['cover_h_in']:.4f}" ({cover['cover_w_px']} × {cover['cover_h_px']} px) |
| Cover finish | matte suits this artwork; glossy lifts the amber |

Spine width follows the page count, so **any edit that changes the page count
changes the cover**. Rebuild both together.

## Files to upload

| Slot | File |
|---|---|
| Kindle eBook manuscript | `build/{c.OUT_EPUB.name}` |
| Kindle eBook cover | `build/{c.LANG}/{c.SLUG}_ebook-cover.jpg` (same image the EPUB embeds) |
| Paperback interior | `build/{c.OUT_INTERIOR.name}` |
| Paperback cover | `build/{c.OUT_COVER.name}` |

Check `build/{c.SLUG}_cover-proof.png` before uploading — it draws the trim
line, the safe area, the spine edges and the ISBN barcode keep-out box.

## Pricing (orientation — confirm against `pricing-notes.md`)

| Format | List (US) | Royalty | Print cost | ≈ Net |
|---|---|---|---|---|
| Kindle | ${eb_list:.2f} | 70% | — | ~${eb_list * 0.70 - 0.06:.2f} |
| Paperback | ${pb_list:.2f} | 60% | ${print_cost:.2f} | ~${pb_list * 0.60 - print_cost:.2f} |

At {pages} pages the print cost is ${print_cost:.2f} — {_vs_estimate(print_cost)} the
~$4.45 `pricing-notes.md` assumed when the book was estimated at 300 pages.
The 70% ebook royalty band requires a list price of $2.99–$9.99, and the ebook
must stay at least 20% below the paperback price.

## Manual steps — these cannot be automated

1. KDP account, then the **tax interview** (W-8BEN if you are not a US person).
   No payment is made until this is complete.
2. Bank and payment details.
3. Create the Kindle title: paste the fields above, upload the EPUB, check it
   in the Kindle Previewer, set territories and price.
4. Create the Paperback from the same title record ("Create Paperback"), so
   the two editions are linked on one product page. Upload interior and cover.
5. Run the **Print Previewer** — it flags trim, bleed and spine problems.
6. Order a proof copy before hitting publish, if you want to see it on paper.
7. Publish. Review takes roughly 24–72 hours.

Do not attempt to script this flow. Browser automation of KDP breaches its
terms of service and risks the account.
"""
    c.BUILD_DIR.mkdir(parents=True, exist_ok=True)
    c.OUT_METADATA.write_text(doc, encoding="utf-8")
